"""In-memory repository for voice_config records (Sub-AC 13c-1).

Seed ontology honored here
--------------------------
``voice_config [object]``: single POV voice 설정 entity.
Fields: voice_id, tone_descriptor, trend_timing_voice, photo_sense_voice,
cta_templates, updated_at.

ToneSwitcher 4톤 폐기 → 1 voice (단일 POV). The operator manages this
singleton via the :class:`InMemoryVoiceConfigRepository` CREATE surface.

Design
------
:class:`VoiceConfigRecord` is the full persisted record shape — it includes
``voice_id`` (auto-generated UUID4) and ``updated_at`` (auto-set timestamp)
alongside the operator-supplied fields.

:class:`VoiceConfigCreateInput` is the *input* DTO (no id, no timestamps —
the repository generates them); it is the type the CREATE function accepts.

:class:`InMemoryVoiceConfigRepository` stores records in a ``dict`` keyed
by ``voice_id``.  It is suitable for unit tests and early operator tooling
without a real database.  A single module-level instance
``voice_config_repo`` is provided for convenience; production code should
inject the repository via dependency injection.

No SQLAlchemy import here — this module is intentionally persistence-layer
agnostic so unit tests can run without a database connection.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone


@dataclass(frozen=True)
class VoiceConfigCreateInput:
    """Operator-supplied fields when creating a new voice_config record.

    These are the *input* values — the repository generates ``voice_id``
    and ``updated_at`` automatically on CREATE.

    Attributes
    ----------
    tone_descriptor:
        Short label that identifies the single editorial voice, e.g.
        ``"트렌드 타이밍 큐레이터"``.
    trend_timing_voice:
        The operator's copy tone for trend-timing communications — how the
        voice talks about *when* a trend is called, e.g.
        ``"아직 아무도 모를 때 먼저 씁니다"``.
    photo_sense_voice:
        The operator's copy tone for photo-craft communications — how the
        voice talks about *composition, light, retouching*, e.g.
        ``"빛의 방향 하나로 분위기가 바뀝니다"``.
    cta_templates:
        Mapping of CTA slot names to template strings.  The template
        strings may reference ``{tone}`` or other voice fields.
        Example: ``{"restyle": "{tone}처럼 restyle해봐"}``.
    """

    tone_descriptor: str
    trend_timing_voice: str
    photo_sense_voice: str
    cta_templates: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class VoiceConfigRecord:
    """Full persisted record for a voice_config entity (ontology: voice_config).

    Extends :class:`VoiceConfigCreateInput` with the repository-generated
    identifier and timestamp fields.

    Attributes
    ----------
    voice_id:
        UUID4 auto-generated by the repository on CREATE.
    tone_descriptor:
        Short label that identifies the single editorial voice.
    trend_timing_voice:
        Copy tone for trend-timing communications.
    photo_sense_voice:
        Copy tone for photo-craft communications.
    cta_templates:
        Mapping of CTA slot names to template strings.
    updated_at:
        UTC datetime set by the repository at CREATE time (and updated on
        every subsequent PATCH — v1 is CREATE-only, so PATCH is deferred).
    """

    voice_id: uuid.UUID
    tone_descriptor: str
    trend_timing_voice: str
    photo_sense_voice: str
    cta_templates: dict[str, str]
    updated_at: datetime


class InMemoryVoiceConfigRepository:
    """In-memory store for :class:`VoiceConfigRecord` objects.

    Provides a ``create`` method that generates ``voice_id`` and
    ``updated_at``, stores the record, and returns it.

    Thread safety
    -------------
    This implementation is NOT thread-safe.  For production use, replace
    the underlying ``dict`` with a proper database session, or wrap the
    dict access with a lock.  For unit tests (single-threaded pytest),
    the current implementation is sufficient.

    Usage
    -----
    >>> repo = InMemoryVoiceConfigRepository()
    >>> inp = VoiceConfigCreateInput(
    ...     tone_descriptor="큐레이터",
    ...     trend_timing_voice="먼저 씁니다",
    ...     photo_sense_voice="빛을 읽습니다",
    ... )
    >>> record = repo.create(inp)
    >>> record.voice_id  # UUID4
    UUID('...')
    >>> record.tone_descriptor
    '큐레이터'
    """

    def __init__(self) -> None:
        self._store: dict[uuid.UUID, VoiceConfigRecord] = {}

    def create(
        self,
        input_: VoiceConfigCreateInput,
    ) -> VoiceConfigRecord:
        """Create a new voice_config record and return it with generated fields.

        Parameters
        ----------
        input_:
            Operator-supplied fields for the new voice_config.

        Returns
        -------
        VoiceConfigRecord
            The persisted record, including the auto-generated ``voice_id``
            (UUID4) and ``updated_at`` (UTC now).

        Notes
        -----
        The returned record is a frozen dataclass — callers cannot mutate
        it after creation. ``cta_templates`` is stored as a shallow copy so
        the caller's original dict cannot alias the stored one.
        """
        record = VoiceConfigRecord(
            voice_id=uuid.uuid4(),
            tone_descriptor=input_.tone_descriptor,
            trend_timing_voice=input_.trend_timing_voice,
            photo_sense_voice=input_.photo_sense_voice,
            # Shallow-copy the dict to break any shared reference with the
            # caller's input dict (frozen dataclass does not deep-copy by default).
            cta_templates=dict(input_.cta_templates),
            updated_at=datetime.now(timezone.utc),
        )
        self._store[record.voice_id] = record
        return record

    def find_by_id(self, voice_id: uuid.UUID) -> VoiceConfigRecord | None:
        """Return the record for ``voice_id``, or ``None`` if absent.

        Parameters
        ----------
        voice_id:
            UUID of the record to look up.

        Returns
        -------
        VoiceConfigRecord | None
            The record, or ``None`` when not found.
        """
        return self._store.get(voice_id)

    def all(self) -> list[VoiceConfigRecord]:
        """Return all stored records as an immutable snapshot list.

        Returns
        -------
        list[VoiceConfigRecord]
            Snapshot of all records in insertion order (Python 3.7+ dict
            preserves insertion order).  Returns an empty list when no
            records have been created.
        """
        return list(self._store.values())

    def delete(self, voice_id: uuid.UUID) -> bool:
        """Delete the record identified by ``voice_id`` from the store.

        Parameters
        ----------
        voice_id:
            UUID of the record to remove.

        Returns
        -------
        bool
            ``True`` when the record existed and was removed;
            ``False`` when no record with that ``voice_id`` was present
            (idempotent — no error is raised for a missing record).
        """
        if voice_id in self._store:
            del self._store[voice_id]
            return True
        return False

    def __len__(self) -> int:
        return len(self._store)


def create_voice_config(
    input_: VoiceConfigCreateInput,
    *,
    repo: InMemoryVoiceConfigRepository,
) -> VoiceConfigRecord:
    """Create a new voice_config record using the given repository.

    This is the service-layer entry point for the CREATE operation.
    It delegates entirely to ``repo.create`` but serves as the single
    named function that the router / operator tooling calls so a future
    swap from in-memory to SQL is a one-line change.

    Parameters
    ----------
    input_:
        Operator-supplied voice_config fields.
    repo:
        The repository to persist into.

    Returns
    -------
    VoiceConfigRecord
        The created record with auto-generated ``voice_id`` and
        ``updated_at``.
    """
    return repo.create(input_)


def get_voice_config(
    voice_id: uuid.UUID,
    *,
    repo: InMemoryVoiceConfigRepository,
) -> VoiceConfigRecord | None:
    """Retrieve a voice_config record by id from the given repository.

    This is the service-layer entry point for the READ operation (Sub-AC
    13c-2). It delegates entirely to ``repo.find_by_id`` but serves as
    the single named function that the router / operator tooling calls so
    a future swap from in-memory to SQL is a one-line change.

    Parameters
    ----------
    voice_id:
        UUID of the voice_config record to retrieve.
    repo:
        The repository to look up from.

    Returns
    -------
    VoiceConfigRecord | None
        The record matching ``voice_id``, or ``None`` when no such record
        exists (not-found case — the caller must handle this as a 404 or
        equivalent application-level not-found response).
    """
    return repo.find_by_id(voice_id)


def delete_voice_config(
    voice_id: uuid.UUID,
    *,
    repo: InMemoryVoiceConfigRepository,
) -> bool:
    """Delete a voice_config record by id from the given repository.

    This is the service-layer entry point for the DELETE operation (Sub-AC
    13c-4). It delegates entirely to ``repo.delete`` but serves as the
    single named function that the router / operator tooling calls so a
    future swap from in-memory to SQL is a one-line change.

    Parameters
    ----------
    voice_id:
        UUID of the voice_config record to delete.
    repo:
        The repository to delete from.

    Returns
    -------
    bool
        ``True`` when the record was found and removed; ``False`` when no
        record with that ``voice_id`` existed (idempotent — callers that
        need a 404 response should check the return value).
    """
    return repo.delete(voice_id)


# ---------------------------------------------------------------------------
# Module-level convenience singleton (unit tests should construct their own)
# ---------------------------------------------------------------------------

#: Module-level in-memory repository instance.
#: Production code should inject via DI; unit tests should construct a fresh
#: ``InMemoryVoiceConfigRepository()`` per test to avoid state leakage.
voice_config_repo: InMemoryVoiceConfigRepository = InMemoryVoiceConfigRepository()


__all__ = [
    "VoiceConfigCreateInput",
    "VoiceConfigRecord",
    "InMemoryVoiceConfigRepository",
    "create_voice_config",
    "get_voice_config",
    "delete_voice_config",
    "voice_config_repo",
]
