/**
 * Public exports for the Glam Up 12단계 결제 깔때기 (한국 변형) state machine.
 */
export {
  FUNNEL_STEPS_ORDERED,
  InvalidTransitionError,
  TOTAL_FUNNEL_STEPS,
  type FunnelEvent,
  type FunnelEventType,
  type FunnelMachine,
  type FunnelProgress,
  type FunnelState,
  type FunnelStepId,
  type FunnelTerminalState,
} from './types.js';
export {
  abandonFunnel,
  advanceStep,
  createFunnel,
  getProgress,
  isTransitionAllowed,
  skipStep,
  startFunnel,
} from './state-machine.js';
export {
  FUNNEL_SCREENS,
  renderAllSteps,
  renderStep,
  type FunnelCta,
  type FunnelCtaAction,
  type FunnelCtaVariant,
  type FunnelScreen,
  type FunnelVariantTag,
} from './screens.js';
export {
  FUNNEL_ANALYTICS_EVENT_TYPES,
  createFunnelAnalytics,
  type AnalyticsSink,
  type CreateFunnelAnalyticsOptions,
  type FunnelAnalytics,
  type FunnelAnalyticsEvent,
  type FunnelAnalyticsEventType,
  type StepCtaClickEvent,
  type StepDropEvent,
  type StepViewEvent,
} from './analytics.js';
export {
  CheckoutGuardError,
  PAYMENT_PLAN_CATALOGUE,
  getPlanPricing,
  triggerCheckout,
  type BillingCadence,
  type CheckoutGuardReason,
  type CheckoutHandoffRequest,
  type CheckoutHandoffResult,
  type HandoffStatus,
  type PaymentGateway,
  type PaymentPlanId,
  type PaymentPlanPricing,
  type TrialBreakdown,
  type TriggerCheckoutOptions,
  type TriggerCheckoutResult,
} from './checkout.js';
export {
  createFunnelOrchestrator,
  runCanonicalKoreanFlow,
  type CreateFunnelOrchestratorOptions,
  type FunnelOrchestrator,
} from './orchestrator.js';
export {
  PAYMENT_EVENT_TYPES,
  PaymentEventSchemaError,
  emitPaymentEvent,
  type CheckoutCompletedEvent,
  type CheckoutCompletedInput,
  type CheckoutStartedEvent,
  type CheckoutStartedInput,
  type EmitPaymentEventOptions,
  type PaymentAnalyticsSink,
  type PaymentEvent,
  type PaymentEventInput,
  type PaymentEventSchemaField,
  type PaymentEventType,
} from './payment-tracking.js';
export {
  ConversionRateError,
  calculateConversionRate,
  calculateConversionRateFromEvents,
  type ConversionRateBreakdown,
  type ConversionRateErrorReason,
  type ConversionRateInput,
} from './conversion-rate.js';
export {
  DEFAULT_NEEDS_ADJUSTMENT_LOWER_BOUND_PERCENT,
  DEFAULT_NORTH_STAR_TARGET_PERCENT,
  ThresholdJudgmentError,
  evaluateConversionRateThreshold,
  isAboveThreshold,
  isFail,
  isPass,
  needsAdjustment,
  type ThresholdJudgment,
  type ThresholdJudgmentErrorReason,
  type ThresholdOptions,
  type ThresholdStatus,
} from './threshold.js';
export {
  DEFAULT_RATING_TRIGGER_CONDITIONS,
  RATING_ACTION_TYPES,
  RATING_TRIGGER_STAGES,
  RatingGateError,
  ZERO_RATING_COUNTERS,
  createRatingGateService,
  evaluateRatingTrigger,
  incrementAction,
  type CreateRatingGateServiceOptions,
  type EvaluateRatingTriggerOptions,
  type RatingActionCounters,
  type RatingActionType,
  type RatingGateErrorReason,
  type RatingGateService,
  type RatingGateSnapshot,
  type RatingTriggerCondition,
  type RatingTriggerDecision,
  type RatingTriggerStage,
} from './rating-gate.js';
export {
  RATING_BRIDGE_PLATFORMS,
  RatingBridgeError,
  createNoopRatingBridge,
  createRatingBridge,
  type CreateRatingBridgeOptions,
  type RatingBridge,
  type RatingBridgeErrorReason,
  type RatingBridgeFailureReason,
  type RatingBridgeNativeBinding,
  type RatingBridgeOutcome,
  type RatingBridgePlatform,
  type RatingBridgeResult,
} from './rating-bridge.js';
export {
  DEFAULT_RATING_PERSISTENCE_KEY,
  EMPTY_RATING_PERSISTED_STATE,
  InMemoryKeyValueStore,
  RATING_PERSISTENCE_SCHEMA_VERSION,
  RatingPersistenceError,
  createRatingPersistence,
  deserializeRatingPersistedState,
  freezeRatingPersistedState,
  serializeRatingPersistedState,
  type CreateRatingPersistenceOptions,
  type KeyValueStore,
  type RatingPersistedState,
  type RatingPersistence,
  type RatingPersistenceErrorReason,
  type RatingPromptStage,
  type RecordPromptInput,
} from './rating-persistence.js';
export {
  RatingHookError,
  useRatingGate,
  type RatingGateController,
  type RatingHookErrorReason,
  type RatingHookListener,
  type RatingHookSnapshot,
  type RatingHookTriggerOutcome,
  type RatingHookTriggerResult,
  type RatingHookUnsubscribe,
  type UseRatingGateOptions,
} from './rating-hook.js';
export {
  ANALYZING_STAGE_DURATION_MS,
  ANALYZING_STAGE_LABELS,
  ANALYZING_TOTAL_DURATION_MS,
  ANALYZING_TOTAL_STAGES,
  CANONICAL_ANALYZING_STAGES,
  createAnalyzingLoader,
  getAnalyzingStage,
  isAnalyzingComplete,
  startAnalyzingLoader,
  tickAnalyzingLoader,
  useAnalyzingLoader,
  type AnalyzingLoaderController,
  type AnalyzingLoaderListener,
  type AnalyzingLoaderScheduler,
  type AnalyzingLoaderState,
  type AnalyzingLoaderUnsubscribe,
  type AnalyzingPhase,
  type AnalyzingStage,
  type AnalyzingStageIndex,
  type UseAnalyzingLoaderOptions,
} from './analyzing-loader.js';
export {
  ANALYZING_LOADER_COMPONENT_TEST_ID,
  AnalyzingLoaderComponentIntegrityError,
  mountAnalyzingLoaderComponent,
  renderAnalyzingLoaderComponent,
  type AnalyzingLoaderComponentHandle,
  type AnalyzingLoaderComponentViewModel,
  type AnalyzingLoaderRenderCallback,
  type AnalyzingLoaderStageItemViewModel,
  type AnalyzingLoaderStageStatus,
  type MountAnalyzingLoaderComponentOptions,
} from './analyzing-loader-component.js';
